import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import LovedTracks from "../components/LovedTracks";
import "semantic-ui-css/semantic.min.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Second Last FM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to my{" "}
          <a href="https://www.last.fm/user/oliverh72">Last FM Profile</a>
        </h1>
      </main>

      <LovedTracks />

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
